connectionSuccessLog       = "An attempt to test the connection with APPS was made and the connection was successful."
connectionFailedLog        = "An attempt to test the connection with APPS was made and the connection was failed."
uploadStartLog             = "=== UPLOAD START on file {file} ==="
uploadEndLog               = "=== UPLOAD END on file {file} ==="
fileDoesNotExistLog        = "The {file} does not exist or has been removed."
fileValidatedLog           = "The file {file} was validated and is being considered a valid file for uploading."
fileNotValidatedLog        = "The file {file} is invalid - {validity}"
compressedLog              = "File {file} was compressed. Decompressing it, so its header can be read."
uploadSuccessLog           = "Successfuly uploaded file {file} to APPS."
addedToQueueSuccessLog     = "Successfuly added file {file} to the uploaded queue."
removedFromQueueSuccessLog = "Successfuly removed file {file} from the uploaded queue."
uuidNotInQueueLog          = "The file {file} was not in the uploaded queue, so cannot be removed from it."
invalidArgLog              = "The value `{arg}` is invalid for argument {argName}. Using default value `{defaultValue}`."
checkStateStartLog         = "=== STATE CHECK START ==="
checkStateStartFileLog     = "Checking file {file}."
checkStateEndLog           = "=== STATE CHECK END ==="
checkStateEndFileLog       = "=== STATE CHECK END on file {file} ==="
stateLog                   = "The file {file} is in the `{state}` state."
approvedSuccessfullLog     = "The file {file} has been verified by APPS and is now approved for processing."
approvedUnsuccessfullLog   = "The file {file} could not be approved for processing."
downloadSuccessfullLog     = "The file {file}'s processed files have been successfully downloaded."
downloadUnsuccessfullLog   = "The file {file}'s processed files could not be downloaded."
dataDeletedSuccessfulLog   = "The file {file} has been deleted from APPS."
dataDeletedUnsuccessfulLog = "Could not delete {file} from APPS."
dataNotFoundLog            = "The file {file} was not found on APPS."
InvalidIdentifierLog       = "The uuid {uuid} is not valid."
criticalExceptionLog       = "Something that wasn't accounted for happened. It's recommended to check what happened to file {file}."
errorFromAPPSLog           = "There was an error with the file {file} in APPS."
fileDataStartLog           = "== GATHERING DATA START on uuid {uuid} =="
fileDataEndLog             = "== GATHERING DATA END on uuid {uuid} =="
approveStartLog            = "== APPROVAL START on file {file} =="
approveEndLog              = "== APPROVAL END on file {file} =="
removeDataStartLog         = "== REMOVE DATA START on file {file} =="
removeDataEndLog           = "== REMOVE DATA END on file {file} =="
retrieveDataStartLog       = "== RETRIEVE DATA START on file {file}"
retrieveDataEndLog         = "== RETRIEVE DATA END on file {file}"