connectionSuccessLog   = "An attempt to test the connection with APPS was made and the connection was successful."
connectionFailedLog    = "An attempt to test the connection with APPS was made and the connection was failed."
uploadStartLog         = "== UPLOAD START on file {file} =="
uploadEndLog           = "== UPLOAD END on file {file} =="
fileDoesNotExistLog    = "The {file} does not exist or has been removed."
fileValidatedLog       = "The file {file} was validated and is being considered a valid file for uploading."
fileNotValidatedLog    = "The file {file} is invalid - {validity}"
compressedLog          = "File {file} was compressed. Decompressing it, so its header can be read."
uploadSuccessLog       = "Successfuly uploaded file {file} to APPS."
addedToQueueSuccessLog = "Successfuly added file {file} to the uploaded queue."
invalidArgLog          = "The value `{arg}` is invalid for argument {argName}. Using default value `{defaultValue}`."
checkStateStartLog     = "== STATE CHECK START on file {file} =="
checkStateEndLog       = "== STATE CHECK END on file {file} =="
approvedLog            = "The file {file} has been verified by APPS and is now approved for processing."